import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { CartDataProvider } from "@/context/useCartDataContext";
import { Manrope } from "next/font/google";
import CartBox from "@/components/CartBox";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "audiophile-ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} text-base text-primary-color min-h-svh flex flex-col`}>
        <CartDataProvider>
          <div className="flex-1">
            <Header></Header>
              {children}
            <CartBox/>
          </div>
        </CartDataProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
